services:
  auth:
    build: .
    container_name: auth-service
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:1234@db:5432/authdb
      - SSL=false
      - PGUSER=postgres
      - PGPASSWORD=1234
      - PGSERVER=db
      - PGPORT=5432
      - PGNAME=authdb
      - JWT_SECRET=brawl_stars
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
